### ISSUE TITLE
Render rented spaces on mainpage

### ISSUE THREAD

**Issue by obernardovieira** [decentramall/decentramall#24]
We now have a demo of what is the goal, but presented with fake data. Once we load all rents with #12 we must recreate the main page

**Comment by raphaelpg** [comment]
The main page will contain all the rents and we can scroll down to untill the last one ?

**Comment by raphaelpg** [comment]
Btw I like the current fake main page as a way to navigate through filters, like you click on the shoes store and it brings you all the stores of that category

**Comment by obernardovieira** [comment]
Lets discuss that on slack. #12 comes first
