### ISSUE TITLE
Learn about Filecoin

### ISSUE THREAD

**Issue by obernardovieira** [decentramall/decentramall#3]
We will explore filecoin and see how it fits the purpose of the project. We might as well consider textile buckets and threadsdb.
*Write feedback on comments*

**Comment by obernardovieira** [comment]
We will be using Slate to work with textile powergate and filecoin. Tutorial here https://www.youtube.com/watch?v=FJjPMKRy8xQ

**Comment by obernardovieira** [comment]
This is a work in progress, but I'll consider it done. Will close and pin.

**Comment by raphaelpg** [comment]
OK !
