### ISSUE TITLE
verify submit rent fields

### ISSUE THREAD

**Issue by obernardovieira** [decentramall/decentramall#50]
https://github.com/decentramall/decentramall/blob/user-profile-navigate/webui/src/components/user/rent.tsx#L24

**Comment by easonchai** [comment]
Also remove cid if rent fails

**Comment by obernardovieira** [comment]
It depends. Depends if we are even uploading it. Because the .stage method does not upload the image. We will have this discussion in our call with Eva.

**Comment by easonchai** [comment]
I think we are already submitting the storage here 
https://github.com/decentramall/decentramall/blob/user-profile-navigate/webui/src/components/user/rent.tsx#L28

**Comment by obernardovieira** [comment]
I know. That's the part that can change. Also because that method will have to change.
